config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to =>'home#index'

  get "dashboard" => "dashboard#index"

  namespace :api, defaults: {format: :json} do
    resources :categories
    resources :cities
    resources :salaries
    resources :companies
    resources :jobs   
    resources :boostcampaings  
    # resources :boosts  
    
    #will show the companies of current_user
    get "dashboard/:user_id" => "dashboard#index"
    
    #will show the jobs of the current_user's company
    get "dashboard/companies/:id" => "dashboard#show"
    
    #will perform the adding a new job function
    post "jobs_add" => "jobs#jobs_add"
    
    #will update the selected job
    post "jobs/edit/:id" => "jobs#update"
    
    #will delete the selected job
    post "jobs/delete/:id" => "jobs#destroy"
    
    #will perform the adding a new company function
    post "companies_add" => "companies#companies_add"
    
    #will update the selected company
    post "companies/edit/:id" => "companies#update"
    
    #
    post "boost_job" => "boostcampaings#boost_job"
    
    #
    get "boosts/:user_id" => "boosts#index"
    post "boosted_job/edit/:id" => "boosts#update"
    
    
    devise_scope :user do
      post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
    end
  end

  resources :jobs do
    resources :boostcampaings do
    end

    resources :boosts do
    end
  end

  resources :companies do
  end
  
  resources :home_companies do 
  end

  resources :dashboard do
  end
  
  resources :home do 
  end
  
  resources :boostcampaings do
  end
  
  resources :boosts do
  end

  namespace :admin do 

    root :to => "panel#index"

    resources :companies do 
    end
    
    resources :jobs do       
    end
    
    resources :boostcampaings do
    end
    
    resources :boosts do
    end
  
  end


end

app/controllers/api/dashboard_controller.rb
class Api::DashboardController < ApplicationController
# before_action :authenticate_user!
  def index
    @companies = Company.my_company(params[:user_id], params[:page])
  end
  
  def show
    @company = Company.find(params[:id])
    @jobs = Job.comp_jobs(@company.id, params[:page])
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :authenticate_user!

  def index
    @companies = Company.my_company(current_user.id, params[:page])
  end

  def show
    @company = Company.find(params[:id])
    @jobs = Job.comp_jobs(@company.id, params[:page])
    @count = Job.comp_jobs_count(@company.id)
    @pending = Job.comp_pending_count(@company.id)
    @campaings = Boostcampaing.boost_campaing_list( current_user.id , params[:page])
  end

end

app/views/dashboard/index.html.erb
  <main>
      <section class="bg-alt">
        <div class="container">

          <div class="row">
            <div class="col-md-6">
              <%= link_to "Manage Your Boosted Jobs", 
              boosts_path, 
              :class=>"btn btn-primary btn-sm btn-inline" 
              %>
              <%= link_to "Create New Company", 
              new_company_path, 
              :class=>"btn btn-success btn-sm btn-inline" 
              %>
            </div>
          </div>

          <div class="row">

            <div class="col-xs-12 text-center">  
            <%= paginate @companies %>
            </div>

          </div>
          <div class="row"> 

            <div class="col-md-12">
              <% @companies.each do |company| %>
                <div class="item-block">
                  <header>
                    <!--
                    <a href="/dashboard/<%= company.id %>">
                      <img src="assets/logo-job.png" alt="" width="160">
                    </a>
                    -->
                    
                    <div class="hgroup">
                      <h4>
                      <a href="/dashboard/<%= company.id %>">
                      <%= company.name  %>
                      </a>                               
                      </h4>
                      <h5>
                        <a href="<%= company.website %>">
                          <%= company.website %>                        
                        </a>
                      </h5>
                    </div>
                    <div class="header-meta">
                      <span class="location">            
                        <%= company.city.name %>
                      </span>
                      <time datetime="2016-03-10 20:00">
                        <%= company.decorated_created_at %>
                      </time>
                    </div>
                  </header>
                  <footer>
                    <!--
                    <p class="status">
                      <strong>Status:</strong> 
                      
                    </p>
                    -->
                    <div class="action-btn">
                      <% if company.user_id == current_user.id %>
                      <a href="/companies/<%= company.id %>/edit" class="btn btn-xs btn-gray">
                        Edit
                        </a>
                      <%= link_to 'Delete', {:action =>'destroy', :id => company.id}, 
                        :confirm =>'Are you sure?', :method =>:delete,:class=>'btn btn-xs btn-danger'
                        %>
                        <% end %>
                    </div>                    
                  </footer>
                </div>  
              <% end %> 
            </div>

          </div>
          <div class="row">

            <div class="col-xs-12 text-center">           
              <%= paginate @companies %>
            </div>

          </div>

        </div>
      </section>
  </main>
<!-- END Main container -->

app/views/dashboard/show.html.erb
<div class="container">
  <div class="row">
    <div class="header-detail m-t-extra">
      <div class="hgroup">
        <h1><a href="#"><%= @company.name %></a></h1>
        <span>
          <a href="#"><%= @company.website %></a>
        </span>
        <i class="fa fa-map-marker"></i>
        <span><%= @company.city.name %></span>
      </div>
      <time datetime="2016-03-03 20:00">
        <%= @company.decorated_created_at %>
      </time>
      <hr>
      <ul class="details cols-2">
        <li>
          <i class="fa fa-map-marker"></i>
          Address:
          <span><%= @company.address %></span>
        </li>
        <li>
          <i class="fa fa-briefcase"></i>
          Company Type:
          <span><%= @company.category.name %></span>
        </li>      
      </ul>
      </p>
    </div>
  </div>  
</div>
<!-- </header> -->
<!-- END Page header -->
<hr>
<!-- Main container -->
<main>
<!-- company detail -->
<section class="no-padder">
  <div class="container">
    <h4>About</h4>
    <p><%= @company.about %></p>
  </div>
</section>
<div class="container">

  <div class="row">

    <div class="col-xs-12 text-center">            
      <h4>Here are Jobs You Submitted!</h4>
    </div>

  </div>
  <div class="col-xs-12 text-center">
    Total Jobs = <%= @count%> 
  </div>
  <div class="row">

    <div class="col-xs-12 text-right">            
      <%= link_to "Add a job", 
      new_job_path, 
      :class=>"btn btn-primary btn-sm" 
      %>
    </div>

  </div>
  <div class="row">
  <% if @pending > 0 %>  
  <b>You have <%= @pending %> pending jobs</b>
  <% end %>
  </div>
  <div class="row">
      <!-- Job detail -->
      <div class="col-md-12">
        <% @jobs.each do |job| %>
        <div class="col-md-6">
          <div class="item-block">
            <header>
              <a href="/jobs/<%= job.id %>">
                <img src="../assets/logo-job.png" alt="" width="160">
              </a>
              <div class="hgroup">
                <h5><a href="/jobs/<%= job.id %>">
                <%= job.title  %>
                </a></h5>
                
                <% if job.company.id == @company.id %>
                <span class="glyphicon glyphicon-user">    
                </span>                            
                <% end %>  
                <h5><%= job.company.name %></h5>
              </div>
              <div class="header-meta">
                <span class="location">            
                  <%= job.city.name %>
                </span>
                <time datetime="2016-03-10 20:00">
                  <%= job.decorated_created_at %>
                </time>
              </div>
            </header>
            <footer>
              <p class="status">
                <strong>Status:</strong> 
                <%= job.status %>
              </p>
              <div class="action-btn">
                <a href="/jobs/<%= job.id %>/edit" class="btn btn-xs btn-gray">  Edit</a>
                  <% if job.status != "BOOSTING"%>
                  <%= link_to 'Boost', new_job_boostcampaing_path(job), :class=>'btn btn-xs btn-danger' %>
                  <%= 
                  #link_to 'Boost', new_job_boostcampaing_path(job), :class=>'btn btn-xs btn-danger'
                   %>
                <% end %>                
                  <%= link_to "delete", {:controller => :jobs,:action => 'destroy', :id => job.id }, :method => :delete,:class=>'btn btn-xs btn-danger',
                    data: { confirm: 'Are you sure you want to delete this alert?' } 
                  %>
              </div>            
            </footer>
          </div>              
        </div>
        <% end %>             
      </div>
    <!-- END Job detail -->
  </div>
    
  <div class="row">
    <div class="col-xs-12 text-center">  
      <%= paginate @jobs %>
    </div>
  </div>
</div>
<!-- END company detail -->
</main>
<!-- END Main container -->
<!-- Back to top button -->
<a id="scroll-up" href="#">
<i class="ti-angle-up"></i></a>
<!-- END Back to top button -->