config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root :to =>'home#index'

  get "dashboard" => "dashboard#index"

  namespace :api, defaults: {format: :json} do
    resources :categories
    resources :cities
    resources :salaries
    resources :companies
    resources :jobs   
    resources :boostcampaings  
    # resources :boosts  
    
    #will show the companies of current_user
    get "dashboard/:user_id" => "dashboard#index"
    
    #will show the jobs of the current_user's company
    get "dashboard/companies/:id" => "dashboard#show"
    
    #will perform the adding a new job function
    post "jobs_add" => "jobs#jobs_add"
    
    #will update the selected job
    post "jobs/edit/:id" => "jobs#update"
    
    #will delete the selected job
    post "jobs/delete/:id" => "jobs#destroy"
    
    #will perform the adding a new company function
    post "companies_add" => "companies#companies_add"
    
    #will update the selected company
    post "companies/edit/:id" => "companies#update"
    
    #
    post "boost_job" => "boostcampaings#boost_job"
    
    #
    get "boosts/:user_id" => "boosts#index"
    post "boosted_job/edit/:id" => "boosts#update"
    
    
    devise_scope :user do
      post 'registrations' => 'registrations#create', :as => 'register'
      post 'sessions' => 'sessions#create', :as => 'login'
      delete 'sessions' => 'sessions#destroy', :as => 'logout'
    end
  end

  resources :jobs do
    resources :boostcampaings do
    end

    resources :boosts do
    end
  end

  resources :companies do
  end
  
  resources :home_companies do 
  end

  resources :dashboard do
  end
  
  resources :home do 
  end
  
  resources :boostcampaings do
  end
  
  resources :boosts do
  end

  namespace :admin do 

    root :to => "panel#index"

    resources :companies do 
    end
    
    resources :jobs do       
    end
    
    resources :boostcampaings do
    end
    
    resources :boosts do
    end
  
  end


end

app/models/job.rb
class Job < ActiveRecord::Base

  belongs_to :city 
  belongs_to :category
  belongs_to :salary_range
  belongs_to :user
  belongs_to :company

  enum job_type: { FULLTIME: 0, PARTTIME: 1 , FREELANCE: 2, INTERNSHIP: 3 }
  enum status: { PENDING: 0, APPROVED: 1 , BOOSTING: 2, BOOSTE_EXPIRED: 3}
  
  validates_presence_of :title, :company_id, :job_type, 
    :category_id, :salary_range_id, :city_id, :description, :requirement, 
    :how_to,:status
    
# for admin approved jobs
  def self.pending_jobs( page = 1) 
    num_jobs = 5
    Job.where("status = ?",0).order( created_at: :DESC )
      .page( page ).per( num_jobs )
  end
# end admin approved jobs
##########################################################################
# for admin approved jobs
  def self.edited_jobs( page = 1) 
    num_jobs = 5
    Job.where("status = ?",1).order( updated_at: :DESC )
      .page( page ).per( num_jobs )
  end
# end admin approved jobs
##########################################################################
# for user dashboard
  def self.my_jobs(user_id, page = 1)
    num_jobs = 5
    Job.where(['user_id = ?', user_id])
      .order(created_at: :DESC)
      .page(page).per(num_jobs)
  end
# end user dashboard
##########################################################################
# for job by company
  def self.comp_jobs( company_id, page = 1 )
    num_jobs = 5
    Job.where("status != ?",0).where(['company_id = ?', company_id])
      .order(created_at: :DESC)
      .page(page).per(num_jobs)
  end
##########################################################################
# comp_jobs_count
  def self.comp_jobs_count( company_id )
    Job.where("status != ?",0).where(['company_id = ?', company_id])
      .order(created_at: :DESC)
      .count
  end
# end comp_jobs_count

#########################################################################
##########################################################################
# comp_jobs_count
  def self.comp_pending_count( company_id )
    Job.where("status = ?",0).where(['company_id = ?', company_id])
      .order(created_at: :DESC)
      .count
  end
# end comp_jobs_count

#########################################################################

# for job display and filter
  def self.get_list( title, category_id, city_id, page = 1)
    num_jobs =  5

    if title == nil && category_id == nil && city_id == nil
    Job.where("status != ?",0)
       .order(boost_budget: :DESC)
       .order(updated_at: :DESC)
        .page(page).per(num_jobs)
    else
      if title != ""
        #with category
        if category_id != ""

          if city_id != ""
            Job.where("status != ?",0)
               .where(['title LIKE ? and category_id = ? and city_id = ?', title, category_id, city_id])
                .order(updated_at: :DESC)
                .page(page).per(num_jobs)
          else
          Job.where("status != ?",0)
            .where(['title LIKE ? and category_id =? ', title, category_id])
            .order(updated_at: :DESC)
            .page(page).per(num_jobs)
          end

        else

          if city_id != ""
            Job.where("status != ?",0)
                .where(['title LIKE ? and city_id = ?', title, city_id])
                .order(updated_at: :DESC)
                .page(page).per(num_jobs)
          else
          Job.where("status != ?",0)
            .where(['title LIKE ?', title])
            .order(updated_at: :DESC)
            .page(page).per(num_jobs)
          end

        end
        #end with category        
      else
          if category_id != ""
            if city_id != ""
              Job.where("status != ?",0)
                 .where(['category_id = ? and city_id = ?', category_id, city_id])
                  .order(updated_at: :DESC)
                  .page(page).per(num_jobs)
            else
              Job.where("status != ?",0)
                 .where(['category_id = ?', category_id])
                  .order(updated_at: :DESC)
                  .page(page).per(num_jobs)
            end
          else
            if city_id != ""
              Job.where("status != ?",0)
                 .where(['city_id = ?', city_id])
                  .order(updated_at: :DESC)
                  .page(page).per(num_jobs)
            else
              Job.where("status != ?",0)
                  .order(updated_at: :DESC)
                  .page(page).per(num_jobs)
            end
            
          end
      end
    end

  end
# end job display and filter
##########################################################################
# for job display and filter
  # def self.get_boost_list( title, category_id, city_id, page = 1)
  #   num_jobs =  5

  #   if title == nil && category_id == nil && city_id == nil
  #   Job.where("status = ?",2)
  #      .order(boost_budget: :DESC)
  #       .page(page).per(num_jobs)
  #   else
  #     if title != ""
  #       #with category
  #       if category_id != ""

  #         if city_id != ""
  #           Job.where("status = ?",2)
  #              .where(['title LIKE ? and category_id = ? and city_id = ?', title, category_id, city_id])
  #               .order(boost_budget: :DESC)
  #               .page(page).per(num_jobs)
  #         else
  #         Job.where("status = ?",2)
  #           .where(['title LIKE ? and category_id =? ', title, category_id])
  #           .order(boost_budget: :DESC)
  #           .page(page).per(num_jobs)
  #         end

  #       else

  #         if city_id != ""
  #           Job.where("status = ?",2)
  #               .where(['title LIKE ? and city_id = ?', title, city_id])
  #               .order(boost_budget: :DESC)
  #               .page(page).per(num_jobs)
  #         else
  #         Job.where("status = ?",2)
  #           .where(['title LIKE ?', title])
  #           .order(boost_budget: :DESC)
  #           .page(page).per(num_jobs)
  #         end

  #       end
  #       #end with category        
  #     else
  #         if category_id != ""
  #           if city_id != ""
  #             Job.where("status = ?",2)
  #                .where(['category_id = ? and city_id = ?', category_id, city_id])
  #                 .order(boost_budget: :DESC)
  #                 .page(page).per(num_jobs)
  #           else
  #             Job.where("status = ?",2)
  #                .where(['category_id = ?', category_id])
  #                 .order(boost_budget: :DESC)
  #                 .page(page).per(num_jobs)
  #           end
  #         else
  #           if city_id != ""
  #             Job.where("status = ?",2)
  #                .where(['city_id = ?', city_id])
  #                 .order(boost_budget: :DESC)
  #                 .page(page).per(num_jobs)
  #           else
  #             Job.where("status = ?",2)
  #                 .order(boost_budget: :DESC)
  #                 .page(page).per(num_jobs)
  #           end
            
  #         end
  #     end
  #   end

  # end
# end job display and filter
##########################################################################
# for date time
  def decorated_created_at
    created_at.to_date.to_s(:long)
    # created_at.strftime "%d/%m/%Y %H:%M"
  end
# end datetime
##########################################################################
# for date time
  def decorated_updated_at
    updated_at.to_date.to_s(:long)
    # created_at.strftime "%d/%m/%Y %H:%M"
  end
# end datetime

##########################################################################

  def self.get_count( title, category_id, city_id, page =1 )
    num_jobs =  5

    if title == nil && category_id == nil && city_id == nil
    Job.where("status = ?",1).order(updated_at: :DESC)
        .count
    else
      if title != ""
        #with category
        if category_id != ""
          if city_id != ""
            Job.where("status = ?",1)
               .where(['title LIKE ? and category_id = ? and city_id = ?', title, category_id, city_id])
                .order(updated_at: :DESC)
                .count
          else
          Job.where("status = ?",1)
            .where(['title LIKE ? and category_id =? ', title, category_id])
            .order(updated_at: :DESC)
            .count
          end
        else
          if city_id != ""
            Job.where("status = ?",1)
                .where(['title LIKE ? and city_id = ?', title, city_id])
                .order(updated_at: :DESC)
                .count
          else
          Job.where("status = ?",1)
            .where(['title LIKE ?', title])
            .order(updated_at: :DESC)
            .count
          end
        end
        #end with category
      else
          if category_id != ""

            if city_id != ""
              Job.where("status = ?",1)
                 .where(['category_id = ? and city_id = ?', category_id, city_id])
                  .order(updated_at: :DESC)
                  .count
            else
              Job.where("status = ?",1)
                 .where(['category_id = ?', category_id])
                  .order(updated_at: :DESC)
                  .count
            end            
          else            
            if city_id != ""
              Job.where("status = ?",1)
                 .where(['city_id = ?', city_id])
                  .order(updated_at: :DESC)
                  .count
            else
              Job.where("status = ?",1)
                  .order(updated_at: :DESC)
                  .count
            end
          end
      end
    end
  end
##########################################################################

end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  before_filter :verify_admin
  def index
    @cities = City.get_list
    @jobs = Job.pending_jobs(params[:page])
    @companies = Company.get_list(params[:page])
    @count = Job.get_count(params[:title], params[:category_id],params[:city_id])
    @edited_jobs = Job.edited_jobs(params[:page])
  end

  def edit
    @job = Job.find(params[:id])    
    @city = City.get_list
    @companies = Company.my_company(current_user.id, params[:page])
  end

  def update
    @job = Job.find(params[:id])    
    @job.status = 1
    respond_to do |format|
      if @job.update(job_params)
        flash[:notic] = ""
        format.html { redirect_to admin_jobs_path, notice: 'Job was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def destroy
    @job = Job.find params[:id]
    @job.destroy
    redirect_to admin_jobs_path
  end

  private
  def job_params
    params.require(:job).permit(:title, :company_name, :company_website, :job_type, 
    :category_id, :salary_range_id, :city_id, :description, :requirement, 
    :how_to,:user_id,:company_id,:status)
  end

  private
  def verify_admin
    redirect_to root_url unless current_user.try(:admin?)
  end

end

app/controllers/api/jobs_controller.rb
class Api::JobsController < ApplicationController
  def index
    @jobs = Job.get_list(params[:title], params[:category_id],params[:city_id] ,params[:page])
    # @boost_jobs = Job.get_boost_list( params[:title], params[:category_id], params[:city_id], params[:page])
  end
  
  def show
    @job = Job.find(params[:id])
  end

  def jobs_add
    @job = Job.new
    @job.title = params["title"]
    @job.company_name = params["company_name"]
    @job.company_website = params["company_website"]
    @job.job_type = params["job_type"].to_i
    @job.category_id = params["category_id"].to_i
    @job.salary_range_id = params["salary_range_id"].to_i
    @job.city_id = params["city_id"].to_i
    @job.description = params["description"]
    @job.requirement = params["requirement"]
    @job.how_to = params["how_to"]   
    @job.user_id = params["user_id"].to_i
    @job.company_id = params["company_id"].to_i
    if @job.save
        render json: {message: "Successfully Added !"}
    else
        render :json => @job.errors
    end 
  end


    def edit
      @job = Job.find(params[:id])    
      @city = City.get_list
      redirect_to edit_job_path
    end

    def update
      @job = Job.find(params[:id])    
        if @job.update(job_params)
          render json: {message: "Successfully Edited!"}
        else
          render :json => @job.errors
        end
    end

    def destroy
      @job = Job.find params[:id]
      if @job.destroy
        render json: {message: "Successfully Deleted!"}
      else
        render json: {message: "Failed to Delete"}
      end
    end

	private
	def job_params
    params.require(:job).permit(:title, :job_type,:category_id, 
                   :salary_range_id, :city_id, :description, :requirement, 
                   :how_to,:company_id,:status)
	end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @cities = City.get_list
    @jobs = Job.get_list(params[:title], params[:category_id], params[:city_id], params[:page])
    @companies = Company.get_list(params[:page])
    @count = Job.get_count(params[:title], params[:category_id], params[:city_id])
  end

  def new
      @job = Job.new
      @cities = City.get_list  
      @companies = Company.my_company(current_user.id, params[:page])  
  end

  def create
    @job = Job.new(job_params)
    @job.user_id = current_user.id
    respond_to do |format|
      if @job.save
        flash[:notic] = ""
        format.html { redirect_to dashboard_path, notice: 'Job was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    @job = Job.find(params[:id])    
    @cities = City.get_list
    @companies = Company.my_company(current_user.id, params[:page])
  end

  def update
    @job = Job.find(params[:id])    
    respond_to do |format|
      if @job.update(job_params)
        flash[:notic] = ""
        format.html { redirect_to dashboard_path, notice: 'Job was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def destroy
    @job = Job.find params[:id]
    @job.destroy
    redirect_to dashboard_path
  end

  private
  def job_params
    params.require(:job).permit(:title, :job_type, :category_id, 
                   :salary_range_id, :city_id, :description,:requirement, 
                   :how_to,:user_id,:company_id,:status)
  end

end

app/views/jobs/_form.html.erb
<!-- Page header -->

  <section class="container page-name">
    <h2 class="text-center">Add a new job</h2>
    <%= simple_form_for @job do |form| %>
      <div class="row">
        <div class="form-group col-xs-12 col-sm-6"> 
          <%= 
            form.input :title, label: false,
            input_html:{class: 'form-control input-lg' },
            placeholder:"Job Title" 
          %>            
        </div>
        <div class="form-group col-xs-12 col-sm-6">
          <%= form.collection_select :category_id,Category.all,
            :id,:name,{prompt: 'Select Job Category'},
            {:class=> 'form-control selectpicker'}
          %>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-xs-12 col-sm-6">
          <%=         
          form.select :company_id, @companies.collect{ |u| [u.name, u.id] },{include_blank: '--Company--'},{:class=>'form-control selectpicker'} 
          %>      
        </div>
        <div class="form-group col-xs-12 col-sm-6">
          <%= form.input :company_website, label: false, input_html:{class: 'form-control input-lg' },
          placeholder:"Company Website"
          %>
        </div>
        <div class="form-group col-xs-12">
         <%= form.input :description, as: :text, label: false, :input_html =>{class: 'form-control',placeholder:"Your Job Description", :cols => 20, :rows => 5 } 
         %>
        </div>         
        <div class="form-group col-xs-12 col-sm-6 col-md-4"> 
          <div class="input-group input-group-sm">
           <span class="input-group-addon">
            <i class="fa fa-briefcase"></i>
           </span>
           <%= form.collection_select :job_type,Job.job_types,:first, :first, :input_html =>{class: 'form-control'} %>
          </div>
        </div>
        <div class="form-group col-xs-12 col-sm-6 col-md-4">
          <div class="input-group input-group-sm">
            <span class="input-group-addon">
              <i class="fa fa-money"></i>
            </span>
            <%= form.collection_select :salary_range_id, SalaryRange.all, :id,:name,{prompt: 'Select a Salary Range'},{:class=> 'form-control selectpicker'}
            %>
          </div>
        </div>
        <div class="form-group col-xs-12 col-sm-6 col-md-4">
          <div class="input-group input-group-sm">
            <span class="input-group-addon">
              <i class="fa fa-map-marker"></i>
            </span>
            <%=     
              form.select :city_id, @cities.collect{ |u| [u.name, u.id] },{include_blank: 'View By City'},{:class=>'form-control selectpicker'} 
            %>
          </div>
        </div>          
        <div class="form-group col-xs-12">
          <%= form.input :requirement, as: :text, label: false, :input_html =>{class: 'form-control',placeholder:"Position Requirements",:cols => 20, :rows => 5 } 
          %>
        </div>
        <div class="form-group col-xs-12">
          <%= form.input :how_to, as: :text,label:false, :input_html =>{class: 'form-control',placeholder:"How to apply",:cols => 20,:rows => 5 } 
          %>
        </div>
        <div class="form-group col-xs-12">
          <p class="text-center">
            <%= form.button :submit,class: "btn btn-success btn-md" %>
          </p>  
        </div>
      </div>
    <% end %>
  </section>


     <!-- END Page header -->
 <!-- END Main container -->
 <!-- Back to top button -->
<a id="scroll-up" href="#">
  <i class="ti-angle-up"></i>
</a>

app/views/jobs/_joblists.html.erb
<!-- Main container -->
    <main>
      <section class="no-padding-top bg-alt">
        <div class="container">
        <div class="row">
          <div class="col-xs-6 text-right">             
            <%= paginate @jobs %>
          </div>
          <div class="col-xs-6 text-right">
            <br>
    <%= link_to "Add a job", new_job_path, :class=>"btn btn-primary btn-sm" %>
          </div>

          <% @jobs.each do |job| %>
          <!-- Job detail -->
          <div class="col-xs-12">
            <div class="item-block">
              <header>
                <a href="/jobs/<%= job.id %>">
                  <img src="../assets/logo-job.png" alt="" width="160">
                </a>
                <div class="hgroup">
                  <h4>
                  <a href="/jobs/<%= job.id %>">
                  <%= job.title  %>
                  </a> 
                  </h4>
                  <h5>
                    <%= job.company_name %>
                  </h5>
                  <% if job.user.id == current_user.id %>
                  <span class="glyphicon glyphicon-user">                    
                  </span>                              
                  <% end %>

                </div>
                <div class="header-meta">
                  <span class="location">                    
                    <%= job.city.name %>
                  </span>
                  <time datetime="2016-03-10 20:00">
                    <%= job.decorated_created_at %>
                  </time>
                </div>
              </header>
              <footer>
                <p class="status">
                  <strong>Status:</strong> 
                  Pending approval hahahaha
                </p>
                <div class="action-btn">
                <% if job.user_id==current_user %>
                <a href="/jobs/<%= job.id %>/edit" class="btn btn-xs btn-gray">
                  Edit
                  </a>
                <%= link_to 'Delete', {:action =>'destroy', :id => job.id}, 
                  :confirm =>'Are you sure?', :method =>:delete,:class=>'btn btn-xs btn-danger'
                  %>
                  <% end %>
                </div>
              </footer>
            </div>
          </div>        <!-- END Job detail -->
        <% end %>   
          <div class="col-xs-6 text-right">             
          <%= paginate @jobs %>
          </div>
        </div>
        </div>
      </section>
    </main>

<!-- END Main container -->

app/views/jobs/index.html.erb
  <!-- Site header -->
    <header class="site-header size-lg text-center">
    <div class="container">

      <div class="row">

        <div class="col-xs-12">
          <form class="header-job-search">
            <div class="input-keyword">             
              <%= text_field_tag :title,params[:title],{:class=>"form-control",placeholder:"View By Job Title" }%>         
            </div>
            <div class="input-location">
              <%= select_tag :city_id, options_from_collection_for_select(City.all, :id, :name, params[:city_id]),{:class=>'form-control',include_blank: 'View By City'} %>
            </div>
            <div class="btn-search">
              <button class="btn btn-primary" type="submit">
                Find jobs
              </button>
            </div>
          </form>
        </div>
        </div>

    </div>
    </header>
  <!-- END Site header -->
<!-- Main container -->
<main>
<!-- Recent jobs -->
<section>
  <div class="container">

      <div class="row item-blocks-connected">

          <div class="col-md-6">
              <div class="col-xs-12">              
                   <%= paginate @jobs %>  
                  We found <%= @count %> total jobs
                <% @jobs.each do |job| %>
                <a class="item-block" href="/jobs/<%= job.id %>" class="job">
                    <header>
                      <img src="assets/logo-google.jpg" alt="">
                      <div class="hgroup">
                        <h4><%= job.title %></h4>
                        <h6><%= job.company.name %></h6>  
                        <% if job.job_type == "FULLTIME" %>
                        <span class="label label-success">
                          <%= job.job_type %>           
                        </span>
                        <% end %>
                        <% if job.job_type == "PARTTIME" %>
                          <span class="label label-warning">
                           <%= job.job_type %>                 
                          </span>
                        <% end %>
                        <% if job.job_type == "FREELANCE" %>
                          <span class="label label-info">
                            <%= job.job_type %>                  
                          </span>
                        <% end %>
                        <% if job.job_type == "INTERNSHIP" %>
                          <span class="label label-danger">
                            <%= job.job_type %>                 
                          </span>
                        <% end %>                                 
                      </div>                      
                      <div class="header-meta">
                        <span class="location">
                          <%= job.city.name %>
                        </span>
                        <time datetime="2016-03-10 20:00">
                          <%= job.decorated_created_at %>
                        </time>
                        <br/>                                       
                      </div>                      
                    </header>                    
                  </a>                  
                <% end %>  
                <%= paginate @jobs %>              
              </div>
          </div>
          <div class="col-md-6">
              <div class="col-xs-12">
                  <%= paginate @companies %>  
                  Total Companies = <%= Company.count %>
                <% @companies.each do |company| %>
                <a class="item-block" href="/companies/<%= company.id %>" id="company" class="company">
                    <header>
                      <img src="assets/logo-google.jpg" alt="">
                      <div class="hgroup">
                        <h4><%= company.name %></h4>
                        <h5><%= company.website %></h5>                              
                      </div>                      
                      <div class="header-meta">
                        <span class="location">
                          <%= company.city.name %>
                        </span>
                        <time datetime="2016-03-10 20:00">
                          <%= company.decorated_created_at %>
                        </time>
                        <br/>                                         
                      </div>                      
                    </header>                    
                  </a>                  
                <% end %>  
                <%= paginate @companies %>              
              </div>
          </div>

      </div>
  </div>
</section>
<!-- END Recent jobs -->

</main>
<!-- END Main container -->

<!-- Back to top button -->
<a id="scroll-up" href="#">
  <i class="ti-angle-up"></i>
</a>
<!-- END Back to top button -->

app/views/jobs/new.html.erb
<!-- Page header -->
  <section class="container page-name">
    <h2 class="text-center">Add a new job</h2>
    <%= render :partial => 'form' %>
  </section>
     <!-- END Page header -->
 <!-- END Main container -->
 <!-- Back to top button -->
<a id="scroll-up" href="#">
  <i class="ti-angle-up"></i>
</a>